export const footerNav = [
  {
    id: 1,
    title: "Register Live or Push",
    link: "",
  },
  {
    id: 2,
    title: "About Ableton",
    link: "",
  },
  {
    id: 3,
    title: "Jobs",
    link: "",
  },
]


export const footerEdu = [
  {
    id: 1,
    title: "Offers for students and teachers",
    link: "",
  },
  {
    id: 2,
    title: "Ableton for the Classroom",
    link: "",
  },
  {
    id: 3,
    title: "Ableton for Colleges and Universities",
    link: "",
  },
]


export const footerComm = [
  {
    id: 1,
    title: "Find Ableton User Groups",
    link: "",
  },
  {
    id: 2,
    title: "Find Certified Training",
    link: "",
  },
  {
    id: 3,
    title: "Become a Certified Trainer",
    link: "",
  },
]


export const countryName = [
  "Algeria",
  "Angola",
  "Benin",
  "Botswana",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cameroon",
  "Central African Republic (the)",
  "Chad",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Côte d'Ivoire",
  "Djibouti",
  "Egypt",
  "Equatorial Guinea",
  "Eritrea",
  "Eswatini",
  "Ethiopia",
  "Gabon",
  "Gambia (the)",
  "Ghana",
  "Guinea",
  "Guinea-Bissau",
  "Kenya",
  "Lesotho",
  "Liberia",
  "Libya",
  "Madagascar",
  "Malawi",
  "Mali",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Morocco",
  "Mozambique",
  "Namibia",
  "Niger (the)",
  "Nigeria",
  "Réunion",
  "Rwanda",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Sao Tome and Principe",
  "Senegal",
  "Seychelles",
  "Sierra Leone",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Sudan (the)",
  "Tanzania, the United Republic of",
  "Togo",
  "Tunisia",
  "Uganda",
  "Western Sahara*",
  "Zambia",
  "Zimbabwe",
  "Antarctica",
  "Bouvet Island",
  "French Southern Territories (the)",
  "Heard Island and McDonald Islands",
  "South Georgia and the South Sandwich Islands",
  "Afghanistan",
  "Armenia",
  "Azerbaijan",
  "Bangladesh",
  "Bhutan",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Cambodia",
  "China",
  "Georgia",
  "Hong Kong",
  "India",
  "Indonesia",
  "Japan",
  "Kazakhstan",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Macao",
  "Malaysia",
  "Maldives",
  "Mongolia",
  "Myanmar",
  "Nepal",
  "Pakistan",
  "Philippines (the)",
  "Singapore",
  "Sri Lanka",
  "Taiwan (Province of China)",
  "Tajikistan",
  "Thailand",
  "Timor-Leste",
  "Turkmenistan",
  "Uzbekistan",
  "Viet Nam",
  "Belize",
  "Central America",
]