export enum VOLUME_ACTION {
  CHANGE = "CHANGE",
  MUTE = "MUTE",
  UNMUTE = "UNMUTE",
}


export enum TRACK_ACTION {
  CHANGE_NEXT = "CHANGE_NEXT",
  CHANGE_PREV = "CHANGE_PREV",
  CHANGE_TO_SONG = "CHANGE_TO_SONG",
  PLAY_PAUSE = "PLAY_PAUSE",
}


export enum MODE_ACTION {
  SHUFFLE = "SHUFFLE",
  REPEAT = "REPEAT",
}


export enum PLAYLIST_ACTION {
  SET = "SET",
}