import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/sidebar'
import AudioControl from '@/components/control'
import { AudioProvider } from '@/context'
import SessionProvider from '@/components/auth/sessionProvider'
import MobileBottomNav from '@/components/mobile-bottom-nav'
import MobileControl from '@/components/control/mobile-control'
import MobileHeader from '@/components/mobile-header'
import MobileDisplay from '@/components/mobile-display'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Spotify Clone',
  description: 'Generated by Neeraj Parmar',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body className={inter.className}>
          <AudioProvider>
            <main className="flex h-screen flex-col overflow-hidden">
              <h1 className="absolute text-center w-full invisible -top-96">Spotify Audio Player Clone</h1>
              {/* desktop view  */}
              <div className="w-full h-full hidden sm:flex flex-col">
                <div className="w-full flex-1 flex overflow-y-auto">
                  {/* menu options (nav) */}
                  <div>
                    <Sidebar />
                  </div>
                  {children}
                </div>
                {/* control box(audio controller) */}
                <AudioControl />
              </div>

              {/* mobile view */}
              <div className="w-full h-full flex sm:hidden">
                <div className='h-full w-full overflow-hidden flex flex-col'>
                  <div className="flex-1 overflow-y-auto pt-20">
                    <MobileHeader />
                    <div className='px-5 py-2'>
                      {children}
                    </div>
                  </div>
                  <div className='h-20 opacity-80 flex justify-between items-center flex-wrap px-2'>
                    <MobileControl />
                  </div>
                  <div className='h-24 opacity-80 flex justify-between items-center flex-wrap px-5'>
                    <MobileBottomNav />
                  </div>
                </div>
              </div>
            </main>
          </AudioProvider>
        </body>
      </SessionProvider>
    </html>
  )
}
